name: Publish Comfy Node
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      # 从官方源码安装，不要用pypi旧包
      - run: pip install git+https://github.com/Comfy-Org/comfy-cli.git
      - run: comfy-cli publish
        env:
          REGISTRY_ACCESS_TOKEN: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
